pluginManagement{
    repositories {
        maven {
            url "https://nexus-emea.mabelbo.net/repository/maven-central/"
        }
        maven {
            url "https://nexus-emea.mabelbo.net/repository/gradle_m2/"
        }
        maven {
            url "https://nexus-emea.mabelbo.net/repository/npm-proxy/"
        }
    }
}