#databaseUrl = jdbc:mysql://localhost:3306/saavy_db
#databaseUserName = mabelLocal
#databasePassword = Tinals00a
#databaseDialect = org.hibernate.dialect.MySQLDialect
#databaseDriver = com.mysql.cj.jdbc.Driver

databaseUrl = jdbc:postgresql://localhost:5432/saavy_db
databaseUserName = postgres
databasePassword = password
databaseDialect = org.hibernate.dialect.PostgreSQLDialect
databaseDriver = org.postgresql.Driver

#databaseUrl = jdbc:h2:file:./build/data/saavy_db
#databaseUserName = sa
#databasePassword =
#databaseDialect = org.hibernate.dialect.H2Dialect
#databaseDriver = org.h2.Driver